app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, HiddenField, SelectField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import DataRequired, NumberRange, Optional

from ..models import Department, Role, Analyse


class DepartmentForm(FlaskForm):
    """
    Form for admin to add or edit a department
    """
    name = StringField('name', validators=[DataRequired()])
    description = StringField('description', validators=[DataRequired()])
    submit = SubmitField('save')


class RoleForm(FlaskForm):
    """
    Form for admin to add or edit a role
    """
    name = StringField('name', validators=[DataRequired()])
    description = StringField('description', validators=[DataRequired()])
    submit = SubmitField('save')


class EmployeeAssignForm(FlaskForm):
    """
    Form for admin to assign departments and roles to employees
    """
    department = QuerySelectField(query_factory=lambda: Department.query.all(),
                                  get_label="name")
    role = QuerySelectField(query_factory=lambda: Role.query.all(),
                            get_label="name")
    submit = SubmitField('save')

class AnalyseForm(FlaskForm):
    """
    Form for admin to add or edit a analyse
    """
    name = StringField('name', validators=[DataRequired()])
    description = StringField('description')
    analyseid = HiddenField()
    submit = SubmitField('save')

# def get_analyses():
#     return Analyse.query

class AssetForm(FlaskForm):
    """
    Form for admin to add or edit a asset
    """
    name = StringField('name', validators=[DataRequired()])
    description = StringField('description')
    #sensitivity = IntegerField('Sensitivity', validators=[DataRequired(),NumberRange(1, 4, '1 - 4')])
    #criticality = IntegerField('Criticality', validators=[DataRequired(),NumberRange(1, 4, '1 - 4')])
    sensitivity = SelectField(u"sensitivity", choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')])
    criticality = SelectField(u"criticality", choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')])
    exposition = HiddenField('exposition')
    #selectedAnalyse = Analyse.query.get(2)
    #analyse_id = IntegerField('Analyse', validators=[DataRequired()])

    # analyse = QuerySelectField(u'Analyse',
    #                                validators=[DataRequired()]
    #                                ,query_factory=lambda: Analyse.query
    #                                ,get_label='name'
    #                                ,allow_blank=True
    #                                ,blank_text=(u'please choose')
    #                                #,default = Analyse.query.filter_by(id=analyse_id).one()
    #                             )

    # analyse_id = HiddenField("Analyse ID")
    #analyse_id = IntegerField("Analyse ID")
    submit = SubmitField('save')

# class AttackerForm(FlaskForm):
#     """
#     Form for admin to add or edit a attacker
#     """
#     name = StringField('Name', validators=[DataRequired()])
#     description = StringField('Description')
#     #wert = StringField('Value Attacker', validators=[DataRequired(),NumberRange(1, 4, '1 - 4')])
#     wert = SelectField(u"Value Attacker", choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')])
#     submit = SubmitField('Save')



class AssetAttackerForm(FlaskForm):
    """
    Form for admin to add or edit a assetattacker
    """
    description = StringField('description')
    #s = StringField('Sensitivity')
    #criticality = StringField('Criticality')
    #wert = IntegerField('Attracktivity Attacker', validators=[DataRequired(),NumberRange(1, 4, '1 - 4')])
    # wert = QuerySelectField(u'Attraktivitaet Angreifer',
    #                                validators=[DataRequired()]
    #                                ,query_factory=[1,2,3,4]
    #                                ,get_label='wert'
    #                                ,allow_blank=True
    #                                ,blank_text=(u'please choose')
    #                                #,default = Analyse.query.filter_by(id=analyse_id).one()
    #                             )
    #filenames = ['1', '2', '3', '4']
    #wert = SelectField(u"Attracktivity Attacker", [Optional()], choices=[(f, f) for f in filenames], default='2')

    wert = SelectField(u"attracktivity attacker", choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')])

    submit = SubmitField('save')

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
import datetime
from flask import abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

#from . import home
from forms import DepartmentForm, EmployeeAssignForm, RoleForm, AnalyseForm, AssetForm, AssetAttackerForm
from .. import db
from ..models import Department, Employee, Role, Analyse, Asset, Attacker, AssetAttacker



from flask import abort, render_template
from flask_login import current_user, login_required

#from app.home.forms import AnalyseForm
from app.models import Analyse, Asset
from . import home

@home.route('/')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title="Welcome")


@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('home/dashboard.html', title="Dashboard")


@home.route('/admin/dashboard')
@login_required
def admin_dashboard():
    # prevent non-admins from accessing the page
    if not current_user.is_admin:
        abort(403)

    return render_template('home/admin_dashboard.html', title="Dashboard")



# Analyse Views


@home.route('/analyses')
@login_required
def list_analyses():
    #check_admin
    """
    List all analyses
    """
    analyses = Analyse.query.filter(Analyse.id > 1)
    return render_template('home/analyses/analyses.html',
                           analyses=analyses, title='Analyses')

@home.route('/analyses_default')
@login_required
def list_analyses_default():
    #check_admin
    """
    List all analyses
    """
    analyses = Analyse.query.filter_by(id=1)
    return render_template('home/analyses/analyses.html',
                           analyses=analyses, title='Analyses')


@home.route('/analyses/add', methods=['GET', 'POST'])
@login_required
def add_analyse():
    """
    Add a analyse to the database
    """
    #check_admin

    add_analyse = True

    form = AnalyseForm()
    if form.validate_on_submit():
        analyse = Analyse(name=form.name.data,
                    description=form.description.data)

        try:
            # add analyse to the database
            db.session.add(analyse)
            db.session.commit()
            flash('You have successfully added a new analyse.')
        except:
            # in case analyse name already exists
            flash('Error: analyse name already exists.')

        # redirect to the analyses page
        return redirect(url_for('home.list_analyses'))

    # load analyse template
    return render_template('home/analyses/analyse.html', add_analyse=add_analyse,
                           form=form, title='Add Analyse')


@home.route('/analyses/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_analyse(id):
    """
    Edit a analyse
    """
    #check_admin

    add_analyse = False

    analyse = Analyse.query.get_or_404(id)
    assets = analyse.assets
    allassets = Analyse.query.get_or_404(1).assets.all()

    form = AnalyseForm(obj=analyse)
    if form.validate_on_submit():
        analyse.name = form.name.data
        analyse.description = form.description.data
        db.session.add(analyse)
        db.session.commit()
        flash('you have successfully edited the analyse.')

        # redirect to the analyses page
        return redirect(url_for('home.list_analyses'))

    form.description.data = analyse.description
    form.name.data = analyse.name
    return render_template('home/analyses/analyse.html', add_analyse=add_analyse,
                           form=form, title="Edit Analyse", assets=assets, allassets=allassets, analyseid=analyse.id)


@home.route('/analyses/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_analyse(id):
    """
    Delete a analyse from the database
    """
    #check_admin

    analyse = Analyse.query.get_or_404(id)
    db.session.delete(analyse)
    db.session.commit()
    flash('You have successfully deleted the analyse.')

    # redirect to the analyses page
    return redirect(url_for('home.list_analyses'))

    return render_template(title="Delete Analyse")





# Asset Views


@home.route('/assets')
@login_required
def list_assets():
    #check_admin
    """
    List all assets
    """
    assets = Asset.query.all()
    for asset in assets:
        if(asset.analyse_id):
            asset.analysename = Analyse.query.filter_by(id=asset.analyse_id).first().name
    return render_template('home/assets/assets.html',
                           assets=assets, title='Assets')

@home.route('/assets/clone/<int:id>/<int:cloneassetid>', methods=['GET', 'POST'])
@login_required
def clone_asset(id, cloneassetid):
    analyse = Analyse.query.get_or_404(id)
    form = AnalyseForm(obj=analyse)

    # clone asset and assign to analyse
    asset = Asset.query.get_or_404(cloneassetid);
    newasset = Asset()
    newasset.name = asset.name + "_CLONED " + datetime.datetime.now().strftime("%I:%M%p on %B %d, %Y")
    newasset.analyse_id = id
    #for a in asset.assetattackers:
    #    newasset.assetattackers.append(a)
    newasset.criticality = asset.criticality
    newasset.sensitivity = asset.sensitivity
    newasset.description = asset.description
    newasset.exposition = asset.exposition
    db.session.add(newasset)
    #db.session.commit()

    attackers = Attacker.query.all()
    for attacker in attackers:
        aa = AssetAttacker.query.filter_by(asset_id=asset.id).filter_by(attacker_id=attacker.id).first()
        if (aa):
            mya = AssetAttacker()
            mya.asset_id=newasset.id
            mya.attacker_id = attacker.id
            mya.description = aa.description
            mya.wert = aa.wert
            db.session.add(mya)
            #db.session.commit()
    db.session.commit()

    add_analyse = False
    assets = analyse.assets
    allassets = Asset.query.all()
    return render_template('home/analyses/analyse.html', add_analyse=add_analyse,
                           form=form, title="Edit Analyse", assets=assets, allassets=allassets, analyseid=id)

@home.route('/assets/add/<int:id>', methods=['GET', 'POST'])
@login_required
def add_asset(id):
    """
    Add a asset to the database
    """
    #check_admin

    add_asset = True

    form = AssetForm()
    if form.validate_on_submit():
        asset = Asset(name=form.name.data,
                    description=form.description.data,
                    analyse_id=id,
                    sensitivity=form.sensitivity.data,
                    criticality=form.criticality.data,
                    )

        try:
            # add asset to the database
            db.session.add(asset)
            db.session.commit()
            flash('You have successfully added a new asset.')
        except:
            # in case asset name already exists
            flash('Error: asset name already exists.')

        # redirect to the assets page
        #return redirect(url_for('home.list_assets'))
        return redirect(url_for('home.edit_analyse', id=id))

    # load asset template
    w, h = 4, 4;
    myscores = [[0 for x in range(w)] for y in range(h)]
    # analyse = Analyse.query.get_or_404(id)
    return render_template('home/assets/asset.html', add_asset=add_asset, myscores=myscores, analyse_id=id,
                           form=form, title='Add Asset')



@home.route('/assets/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_asset(id):
    """
    Edit a asset
    """
    #check_admin

    add_asset = False

    asset = Asset.query.get_or_404(id)
    analyse = Analyse.query.get_or_404(asset.analyse_id)
    attackers = Attacker.query.all()
    form = AssetForm(obj=asset)
    if form.validate_on_submit():
        asset.name = form.name.data
        asset.description = form.description.data
        #asset.analyse_id = form.analyse_id.data
        asset.criticality = form.criticality.data
        asset.sensitivity = form.sensitivity.data
        myexpsum = 0.0
        myexparr = [0,0,0,0]
        for attacker in attackers:
            myassetattacker = AssetAttacker.query.filter_by(asset_id=id).filter_by(
                attacker_id=attacker.id).first()

            myexparr[attacker.wert-1] = max(myexparr[attacker.wert-1], myassetattacker.wert)

        risk = myexparr[0] + myexparr[1]*2 + myexparr[2]*3 + myexparr[3]*4
        wu = max(form.criticality.data, form.sensitivity.data)
        myexpsum = (int(wu) * risk)

        asset.exposition =  myexpsum / 10.0
        db.session.add(asset)
        db.session.commit()
        #flash('You have successfully edited the asset.')

        # redirect to the asset page
        #return redirect(url_for('home.list_assets'))

        #asset = Asset.query.get(assetattacker.asset_id)
        return redirect(url_for('home.edit_analyse', id=asset.analyse_id))

    form.description.data = asset.description
    form.name.data = asset.name
    #analyse = Analyse.query.get(asset.analyse_id)
    #form.analyse.default = asset.analyse_id # trying to set default select value
    form.sensitivity.data = str(asset.sensitivity)
    form.criticality.data = str(asset.criticality)
    form.exposition.data = asset.exposition

    # add an assetattacker per asset and attackers
    # get current asset.id id
    w, h = 4, 4;
    myscores = [[0 for x in range(w)] for y in range(h)]
    for attacker in attackers:
        attacker.myassetattacker = AssetAttacker.query.filter_by(asset_id=id).filter_by(attacker_id=attacker.id).first()
        if not(attacker.myassetattacker):
            mya = AssetAttacker()
            mya.asset_id=id
            mya.attacker_id = attacker.id
            mya.wert = -1
            db.session.add(mya)
            db.session.commit()

        try:
            #myscores[   max((attacker.myassetattacker.wert-1),0)   ][asset.wa-1] = "True"
            for myassetattackervaluemax in range(0,max((attacker.myassetattacker.wert),0)):

app/templates/home/analyses/analyse.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    {% if add_department %}
        add analyse
    {% else %}
        edit analyse
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_analyse %}
                <h1>add analyse</h1>
            {% else %}
                <h1>edit analyse</h1>
            {% endif %}

            {{ wtf.quick_form(form) }}



        {% if assets %}
            <h1>assets</h1>
          <hr class="intro-divider">

            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="15%"> name </th>
                  <th width="40%"> description </th>
                  <th width="15%"> sensitivity </th>
                  <th width="15%"> criticality </th>
                  <th width="15%"> exposition </th>
                  <th width="15%"> edit </th>
                  <th width="15%"> delete </th>
                </tr>
              </thead>
              <tbody>
              {% for asset in assets %}
                <tr>
                    <td> {{ asset.name }} </td>
                    <td> {{ asset.description }} </td>
                    <td> {{ asset.sensitivity }} </td>
                    <td> {{ asset.criticality }} </td>
                    <td> {{ asset.exposition }} </td>
                    <td>
                    <a href="{{ url_for('home.edit_asset', id=asset.id) }}">
                      <i class="fa fa-pencil"></i> edit
                    </a>
                    </td>
                    <td>
                    <a href="{{ url_for('home.delete_asset', id=asset.id) }}">
                      <i class="fa fa-trash"></i> delete
                    </a>
                    </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>

          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            {% if not add_analyse %}
                <h3> No assets have been added. </h3>
                <hr class="intro-divider">
            {% endif %}
        {% endif %}
          {% if not add_analyse %}
            <a href="{{ url_for('home.add_asset', id=analyseid) }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            +
            </a>
              <br/>
            <select id="cloneassetid" name="cloneassetid">
                {% for asset in allassets %}
                <option value="{{ asset.id }}">{{ asset.name }}</option>
                {% endfor %}
            </select>
            <button id="clonebutton" name="clonebutton" class="btn btn-default btn-lg" theurl="{{ url_for('home.clone_asset', id=analyseid, cloneassetid='0') }}">
            <i class="fa fa-plus"></i>
            + from template
            </button>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home/analyses/analyses.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Analyses{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">analysis</h1>
        {% if analyses %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="15%"> name </th>
                  <th width="40%"> description </th>
                  <th width="15%"> asset count </th>
                  <th width="15%"> edit </th>
                  <th width="15%"> delete </th>
                </tr>
              </thead>
              <tbody>
              {% for analyse in analyses %}
                <tr>
                  <td> {{ analyse.name }} </td>
                  <td> {{ analyse.description }} </td>
                  <td>
                    {% if analyse.assets %}
                      {{ analyse.assets.count() }}
                    {% else %}
                      0
                    {% endif %}
                  </td>
                  <td>
                    <a href="{{ url_for('home.edit_analyse', id=analyse.id) }}">
                      <i class="fa fa-pencil"></i> edit
                    </a>
                  </td>
                  <td>
                    <a href="{{ url_for('home.delete_analyse', id=analyse.id) }}">
                      <i class="fa fa-trash"></i> delete
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No analyses have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('home.add_analyse') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            add analyse
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}